apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-bot-config
  namespace: discord-bot
data:
  NODE_ENV: "production"
  N8N_TEST_API: "https://n8n.tarchunk.win/webhook-test/2e540deb-3f14-4879-ad51-dd3bd1df2a96"
  N8N_PRODUCTION_API: "https://n8n.tarchunk.win/webhook/2e540deb-3f14-4879-ad51-dd3bd1df2a96"