apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secrets
  namespace: discord-bot
type: Opaque
data:
  DISCORD_TOKEN: MTI5OTk0OTgxOTE0MTU1NDE5Nw.GgKhjj.XIrPZQDbHCiFmCz5Vgrftl52Nwq2naJ8_IvUVA
stringData:
  DISCORD_TOKEN: "MTI5OTk0OTgxOTE0MTU1NDE5Nw.GgKhjj.XIrPZQDbHCiFmCz5Vgrftl52Nwq2naJ8_IvUVA"